# This is a regular template file, which shows only the most important configuration entries.
#
# Author: Red Hat Product Security
#
# Additional configuration options are available, as shown in "config-template-long.yaml".
# All the values are optional (except `config.configVersion`): if a key is missing, it will mean either "disabled" or a sensible default will be selected

config:
  # WARNING: `configVersion` indicates the schema version of the config file.
  # This value tells RapiDAST what schema should be used to read this configuration.
  # Therefore you should only change it if you update the configuration to a newer schema
  # It is intended to keep backward compatibility (newer RapiDAST running an older config)
  configVersion: 5

# `application` contains data related to the application, not to the scans.
application:
  shortName: "MyApp-1.0"
  url: "https://$CONSOLE_URL/api/kubernetes"

# `general` is a section that will be applied to all scanners.
general:

  # See the config-template-long.yaml for more authentication options
  authentication:
    type: "cookie"
    parameters:
        name: "openshift-session-token"
        value: "$TOKEN"  # referring to a env defined in general.environ.envFile


  container:
    # This configures what technology is to be used for RapiDAST to run each scanner.
    # Currently supported: `podman`, `flatpak` and `none`
    #   podman: RapiDAST runs each scanner using podman
    #   flatpak: RapiDAST runs each scanner using flatpak
    #   none: RapiDAST runs each scanner in the same host or container (where RapiDAST itself is running in a container)
    type: "podman"

# `scanners' is a section that configures scanning options
# See the config-template-long.yaml for more options
scanners:
  zap:
    apiScan:
      apis:
        apiUrl: "$API_URL"
        # alternative: apiFile: "<local path to openAPI file>"

    passiveScan:
      # optional list of passive rules to disable
      disabledRules: "2,10015,10027,10096,10024"

    # Enable activeScan by uncommenting, once scans with the passiveScan only has run successfully
    #  # If no policy is chosen, a default ("API-scan-minimal") will be selected
    #  # The list of policies can be found in scanners/zap/policies/
    activeScan:
     policy: "API-scan-minimal"

    
    container:
      parameters:
        image: "docker.io/owasp/zap2docker-stable:latest" # for type such as podman

        executable: "zap.sh"  # for Linux
        # executable: "/Applications/OWASP ZAP.app/Contents/Java/zap.sh"    # for MacOS, when general.container.type is 'none' only


    report:
      format: ["json", "html"]
      # format: ["json","html","sarif","xml"]  # default: "json" only