apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    labels:
      machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
      machine.openshift.io/cluster-api-machine-role: infra
      machine.openshift.io/cluster-api-machine-type: infra
    name: ${CLUSTER_NAME}-infra-1
    namespace: openshift-machine-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
        machine.openshift.io/cluster-api-machineset: ${CLUSTER_NAME}-infra-${CLUSTER_REGION}
    template:
      metadata:
        labels:
          machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
          machine.openshift.io/cluster-api-machine-role: infra
          machine.openshift.io/cluster-api-machine-type: infra
          machine.openshift.io/cluster-api-machineset: ${CLUSTER_NAME}-infra-${CLUSTER_REGION}
      spec:
        metadata:
          labels:
            node-role.kubernetes.io/infra: ''
        providerSpec:
          value:
            apiVersion: ibmcloudproviderconfig.openshift.io/v1beta1
            credentialsSecret:
              name: ibmcloud-credentials
            image: ${CLUSTER_NAME}-rhcos
            kind: IBMCloudMachineProviderSpec
            primaryNetworkInterface:
              securityGroups:
                - ${CLUSTER_NAME}-sg-cluster-wide
                - ${CLUSTER_NAME}-sg-openshift-net
              subnet: ${CLUSTER_NAME}-subnet-compute-${CLUSTER_REGION}-1
            profile: ${OPENSHIFT_INFRA_NODE_INSTANCE_TYPE}
            region: ${CLUSTER_REGION}
            resourceGroup: ${CLUSTER_NAME}
            userDataSecret:
              name: worker-user-data
            vpc: ${CLUSTER_NAME}-vpc
            zone: ${CLUSTER_REGION}-1
          taints:
            - key: node-role.kubernetes.io/infra
              effect: NoSchedule
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    labels:
      machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
      machine.openshift.io/cluster-api-machine-role: infra
      machine.openshift.io/cluster-api-machine-type: infra
    name: ${CLUSTER_NAME}-infra-2
    namespace: openshift-machine-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
        machine.openshift.io/cluster-api-machineset: '${CLUSTER_NAME}-infra-${CLUSTER_REGION}'
    template:
      metadata:
        labels:
          machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
          machine.openshift.io/cluster-api-machine-role: infra
          machine.openshift.io/cluster-api-machine-type: infra
          machine.openshift.io/cluster-api-machineset: '${CLUSTER_NAME}-infra-${CLUSTER_REGION}'
      spec:
        metadata:
          labels:
            node-role.kubernetes.io/infra: ''
        providerSpec:
          value:
            apiVersion: ibmcloudproviderconfig.openshift.io/v1beta1
            credentialsSecret:
              name: ibmcloud-credentials
            image: '${CLUSTER_NAME}-rhcos'
            kind: IBMCloudMachineProviderSpec
            primaryNetworkInterface:
              securityGroups:
                - '${CLUSTER_NAME}-sg-cluster-wide'
                - '${CLUSTER_NAME}-sg-openshift-net'
              subnet: '${CLUSTER_NAME}-subnet-compute-${CLUSTER_REGION}-2'
            profile: '${OPENSHIFT_INFRA_NODE_INSTANCE_TYPE}'
            region: '${CLUSTER_REGION}'
            resourceGroup: ${CLUSTER_NAME}
            userDataSecret:
              name: worker-user-data
            vpc: '${CLUSTER_NAME}-vpc'
            zone: '${CLUSTER_REGION}-2'
          taints:
            - key: node-role.kubernetes.io/infra
              effect: NoSchedule
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    labels:
      machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
      machine.openshift.io/cluster-api-machine-role: infra
      machine.openshift.io/cluster-api-machine-type: infra
    name: '${CLUSTER_NAME}-infra-3'
    namespace: openshift-machine-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
        machine.openshift.io/cluster-api-machineset: '${CLUSTER_NAME}-infra-${CLUSTER_REGION}'
    template:
      metadata:
        labels:
          machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
          machine.openshift.io/cluster-api-machine-role: infra
          machine.openshift.io/cluster-api-machine-type: infra
          machine.openshift.io/cluster-api-machineset: '${CLUSTER_NAME}-infra-${CLUSTER_REGION}'
      spec:
        metadata:
          labels:
            node-role.kubernetes.io/infra: ''
        providerSpec:
          value:
            apiVersion: ibmcloudproviderconfig.openshift.io/v1beta1
            credentialsSecret:
              name: ibmcloud-credentials
            image: '${CLUSTER_NAME}-rhcos'
            kind: IBMCloudMachineProviderSpec
            primaryNetworkInterface:
              securityGroups:
                - '${CLUSTER_NAME}-sg-cluster-wide'
                - '${CLUSTER_NAME}-sg-openshift-net'
              subnet: '${CLUSTER_NAME}-subnet-compute-${CLUSTER_REGION}-3'
            profile: '${OPENSHIFT_INFRA_NODE_INSTANCE_TYPE}'
            region: '${CLUSTER_REGION}'
            resourceGroup: ${CLUSTER_NAME}
            userDataSecret:
              name: worker-user-data
            vpc: '${CLUSTER_NAME}-vpc'
            zone: '${CLUSTER_REGION}-3'
          taints:
            - key: node-role.kubernetes.io/infra
              effect: NoSchedule