apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rapidast-operator
  namespace: rapidast
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: rapidast-operator
  source: rapidast-catalog
  sourceNamespace: rapidast